# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{find_by_hash}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Bigg"]
  s.date = %q{2010-01-12}
  s.description = %q{Extension to ActiveRecord to allow you to do findy-thingies with hashes}
  s.email = %q{radarlistener@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "find_by_hash.sqlite3",
     "lib/find_by_hash.rb",
     "rails/init.rb",
     "spec/find_by_hash_spec.rb",
     "spec/initializers/schema.rb",
     "spec/spec_helper.rb",
     "spec/support/models.rb"
  ]
  s.homepage = %q{http://github.com/radar/find_by_hash}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Extension to ActiveRecord to allow you to do findy-thingies with hashes}
  s.test_files = [
    "spec/find_by_hash_spec.rb",
     "spec/initializers/schema.rb",
     "spec/spec_helper.rb",
     "spec/support/models.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 0"])
  end
end
